/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "surface-container-highest": "#e4e2e3",
        "tertiary-fixed": "#cfe5ff",
        "on-background": "#1b1c1d",
        "on-tertiary-fixed-variant": "#34495e",
        "on-tertiary-container": "#93a9c1",
        "surface-tint": "#4e6073",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface": "#fbf9fa",
        "primary-fixed": "#d1e4fb",
        "secondary-fixed-dim": "#92ccff",
        "secondary-fixed": "#cce5ff",
        "on-primary-fixed": "#091d2e",
        "inverse-on-surface": "#f2f0f2",
        "on-tertiary-fixed": "#051d30",
        "tertiary-fixed-dim": "#b3c9e2",
        "primary-fixed-dim": "#b5c8df",
        "on-primary-container": "#96a9be",
        "on-primary-fixed-variant": "#36485b",
        "primary-container": "#2c3e50",
        "secondary": "#006397",
        "surface-container": "#efedef",
        "on-surface": "#1b1c1d",
        "on-tertiary": "#ffffff",
        "background": "#fbf9fa",
        "inverse-surface": "#303032",
        "tertiary-container": "#293e53",
        "on-secondary-fixed": "#001d31",
        "outline": "#74777d",
        "surface-dim": "#dbd9db",
        "surface-variant": "#e4e2e3",
        "on-secondary-container": "#00476e",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#43474c",
        "surface-container-high": "#e9e8e9",
        "on-secondary-fixed-variant": "#004b73",
        "primary": "#162839",
        "outline-variant": "#c4c6cd",
        "surface-container-low": "#f5f3f4",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "secondary-container": "#5cb8fd",
        "tertiary": "#12283c",
        "inverse-primary": "#b5c8df",
        "surface-bright": "#fbf9fa",
        "on-error-container": "#93000a",
        "accent": "#e74c3c",
        "success": "#27ae60",
        "warning": "#f39c12",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        md: "16px",
        container_padding: "30px",
        xl: "32px",
        xs: "4px",
        lg: "24px",
        sm: "8px",
        base: "4px",
      },
      fontFamily: {
        sans: ["Lexend", "Montserrat", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        lexend: ["Lexend", "sans-serif"],
        label: ["Lexend"],
        body: ["Lexend"],
        display: ["Lexend"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "1", fontWeight: "600" }],
        "label-bold": ["12px", { lineHeight: "1", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "h2": ["20px", { lineHeight: "1.3", fontWeight: "700" }],
        "h1": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "h3": ["16px", { lineHeight: "1.4", fontWeight: "600" }],
      },
      boxShadow: {
        DEFAULT: "0 2px 12px rgba(0, 0, 0, 0.06)",
        lg: "0 8px 30px rgba(0, 0, 0, 0.12)",
        sm: "0 1px 4px rgba(0,0,0,0.04)",
        stat: "0 2px 12px rgba(0,0,0,0.06)",
      },
    },
  },
  plugins: [],
};
