import { environment } from '../../environments/environment';

export const API_URL = environment.apiUrl;

export const API_ENDPOINTS = {
  AUTH_LOGIN: `${API_URL}/api/auth/login`,
  AUTH_VALIDATE: `${API_URL}/api/auth/validate-token`,
  USUARIO_PRE_REGISTRO: `${API_URL}/api/usuario/pre-registro`,
  USUARIO_RETOMAR_PAGO: `${API_URL}/api/usuario/retomar-pago`,
  USUARIO_EXISTE_DNI: (dni: number) => `${API_URL}/api/usuario/existe-dni/${dni}`,
  USUARIO_EXISTE_EMAIL: (email: string) => `${API_URL}/api/usuario/existe-email?email=${encodeURIComponent(email)}`,
  USUARIO_EXISTE_TELEFONO: (telefono: string) => `${API_URL}/api/usuario/existe-telefono?telefono=${encodeURIComponent(telefono)}`,
  USUARIO_ACTIVAR: (dni: number) => `${API_URL}/api/usuario/activar/${dni}`,
  USUARIO_PERFIL: (dni: number) => `${API_URL}/api/usuario/perfil/${dni}`,
  ADMIN_USUARIOS: `${API_URL}/api/admin/usuarios`,
  ADMIN_USUARIO: (dni: number) => `${API_URL}/api/admin/usuarios/${dni}`,
  ADMIN_ACTIVAR: (dni: number) => `${API_URL}/api/admin/usuarios/${dni}/activar`,
  ADMIN_ELIMINAR: (dni: number) => `${API_URL}/api/admin/usuarios/${dni}/eliminar`,
  ADMIN_PERSONAL: `${API_URL}/api/admin/personal`,
  ADMIN_PERSONAL_DNI: (dni: number) => `${API_URL}/api/admin/personal/${dni}`,
  ADMIN_PERSONAL_DESACTIVAR: (dni: number) => `${API_URL}/api/admin/personal/${dni}/desactivar`,
  ADMIN_ESTADISTICAS: `${API_URL}/api/admin/usuarios/estadisticas`,
  ADMIN_ESTADISTICAS_COMPLETAS: `${API_URL}/api/admin/estadisticas/completas`,
  ADMIN_INGRESOS_MENSUALES: `${API_URL}/api/admin/estadisticas/ingresos-mensuales`,
  ADMIN_CLASES_POPULARES: `${API_URL}/api/admin/estadisticas/clases-populares`,
  ADMIN_MEMBRESIAS: `${API_URL}/api/admin/membresias`,
  ADMIN_POR_ESTADO: (estado: string) => `${API_URL}/api/admin/usuarios/estado/${estado}`,
  CLASES: `${API_URL}/api/clases`,
  CLASES_TRAINER: (idTrainer: number) => `${API_URL}/api/clases/trainer/${idTrainer}`,
  CLASE: (id: number) => `${API_URL}/api/clases/${id}`,
  INSCRIPCIONES: `${API_URL}/api/inscripciones`,
  INSCRIPCIONES_INSCRIBIR: (dni: number, idClase: number) => `${API_URL}/api/inscripciones/inscribir?dniUsuario=${dni}&idClase=${idClase}`,
  INSCRIPCIONES_CANCELAR: (dni: number, idClase: number) => `${API_URL}/api/inscripciones/cancelar?dniUsuario=${dni}&idClase=${idClase}`,
  INSCRIPCIONES_USUARIO_ACTIVAS: (dni: number) => `${API_URL}/api/inscripciones/usuario/${dni}/activas`,
  INSCRIPCIONES_CLASE: (idClase: number) => `${API_URL}/api/inscripciones/clase/${idClase}`,
  INSCRIPCIONES_CLASE_CUPOS: (idClase: number) => `${API_URL}/api/inscripciones/clase/${idClase}/cupos`,
  INSCRIPCIONES_VERIFICAR: (dni: number, idClase: number) => `${API_URL}/api/inscripciones/verificar/${dni}/${idClase}`,
  PAYMENT_CREATE: (plan: string) => `${API_URL}/api/payment/create-checkout-session/${plan}`,
  PAYMENT_CONFIRM: `${API_URL}/api/payment/confirm`,
  PAYMENT_LAST: `${API_URL}/api/payment/last-payment`,
  PAYMENT_ALL: `${API_URL}/api/payment/all`,
  MEMBRESIA_ACTIVA: (dni: number) => `${API_URL}/api/stripe/membresia-activa/${dni}`,
};